### PR TITLE
Adds ts typings and removes now unused webpack dev dependencies 

### PR DESCRIPTION
**Pull request by hirako2000**
- this adds some rudimentary types for #4
- removes left over webpack deps

### CODE REVIEW

**Comment by hirako2000** [comment]
I will share a working boilerplate.

**Comment by hirako2000** [comment]
I've pushed this repo as a working project: (https://github.com/hirako2000/test-yoffee-ts)

It works fine on my side

**Comment by hirako2000** [comment]
and I'm not sure about the issue with commonJS and tsc, but perhaps this config is what does the trick:
```json
{
    "compilerOptions": {
      "rootDir": "src",
      "outDir": "lib",
      "declaration": true,
      "resolveJsonModule": true,
      "strict": true,
      "esModuleInterop": true, // this
      "downlevelIteration": true,
      "pretty": true
    },
    "exclude": [
      "tests"
    ],
    "include": [
        "src",
    ]
  }
```

**Comment by hirako2000** [comment]
As we are on the subject of modules and transpiler issues and the surprising lack of browser support, please note that for user convenience, it is why the rollup changes included building more than what webpack was configured to do which was picking one flavor of distribution of the lib and the hell with developers who dislike that single flavor :) 

Instead of pushing the problem to the consumer pipeline in handling a particular type of module system, the build now outputs a default ESM library (because this standard is officially chosen to be natively supported by node and other vendors, hence is winning the long race over commonJS)
But we also output a CommonJS distrib, because many developers still use commonJS, usually for the browser but even on node, they are familiar with it, and still are confused with ESM, and refuse to make the jump, despite the fact bundlers have an easier time doing tree-shacking on ES modules. 
We also output an UMD flavour, because it is "universal" and claims to be working fine both on front end stack and back end stack, and I think is also adopted officially. Some say that UMD should be enough, but see it adds some overhead to the bytesize, and I'm not convinced it just works anywhere, yet. 
And, we also output a module-less version of it, so any browser out there can interpret it as is. without the need of dependencies or having to do any transpiling to ensure backward compatibilities.

AFAIK AMD isn't that important because asynchronous module loading isn't very commonly used by developers, and those who do certainly know about this whole topic and can figure out their bundling config to easily asynchronously load whatever they bits they want. 

It is a sad state of affaire that nearly a decade after module system specs were define and became the new way to articulate javascript code compartments, we still have to consider multiple patterns. 

I suggest to document the existence of the several flavors so that consumers may be directed to their flavor of choice. 

Back to your issue:

1/ Ensure to tell tsc what to do with ES modules (I think you figured that right) 2/ Make sure to transpile accordingly for browser compatibility, either via ts config, or use babel taking  tsc's output. 

Alternatively, for 1/
Don't use the ESM distrib, instead:
a/ require() the CJS flavor. 
or
b/ inject the iief as is. 
or
c/ try importing the UMD flavor (i have no idea what tsc may do, it may not like it either, but tsc is funny at times) 

Alternatively, for all, do what I did, life is too short, just adopt parcel 🦅

**Comment by lefetmeofefet** [comment]
Thanks for the example, and for introducing me parcel! it's awesome. Actually the only problem I had is with resolving bare imports, and parcel fixes that by default. I also tried stripping as much to see what was really necessary to work with ts, so here is a fully stripped down version: https://github.com/lefetmeofefet/yoffee-typescript-template

**Comment by hirako2000** [comment]
Great job simplifying the boilerplate to bare minimum. I think it should be promoted as demo boilerplate to demonstrate functionalities. we could cover other features of the library like you did on the in browser examples. same but in a boilerplate project :)

parcel and vite are my favorite bundlers today, for web apps. they don't have the config complications of webpack, execute way faster, and produce minimal bytes. rollup is best for building lean libraries.

**Comment by lefetmeofefet** [comment]
Vite looks a bit more framework-y but also lean and modern. Interesting.
Actually demos is a really nice way to help the potential community. I think I'll link each demo from the website to a working repo to clone

**Pull request merged**
